import { DEFAULT_THEME, resolveTheme } from '../../../packages/customization/src';
import { useCustomizationState } from '../../state/customization-hooks';
import { customizationService } from '../../state/customization-service';
import { SettingHelp, SettingSwitch } from './SettingControls';
import { TrophyGlyph } from '../TrophyGlyph';

export function VisualSettings() {
  const { config } = useCustomizationState();
  const v = config.visual;
  const theme = resolveTheme(config.themeId);
  const set = (patch:Partial<typeof v>) => void customizationService.setVisual(patch);
  return <section className="stt-settings-section">
    <fieldset className="stt-setting-group"><legend>Controls & accessibility</legend><div className="stt-settings-grid">
      <label className="stt-field">Settings navigation <SettingHelp text="Keep sections in top tabs or a left sidebar. Small windows always use top tabs." /><select value={v.settingsOrganization} onChange={e => set({settingsOrganization:e.target.value as typeof v.settingsOrganization})}><option value="tabs">Top tabs</option><option value="sidebar">Left sidebar</option></select></label>
      <label className="stt-field">Toggle controls <SettingHelp text="Use compact sliding switches or familiar checkboxes across Trophies." /><select value={v.toggleStyle} onChange={e => set({toggleStyle:e.target.value as typeof v.toggleStyle})}><option value="switch">Switches</option><option value="checkbox">Checkboxes</option></select></label>
      <SettingSwitch label="Question mark cursor" help="Show the help cursor over hints and achievement previews. Turning it off keeps tooltips working." checked={v.helpCursor} onChange={helpCursor => set({helpCursor})} />
      <label className="stt-field">Color-blind support <SettingHelp text="Try an alternative trophy palette with B, S, G and P labels. Choose what reads best for you; manual trophy and border colors still win." /><select value={v.colorBlindMode} onChange={e => set({colorBlindMode:e.target.value as typeof v.colorBlindMode})}><option value="off">Off</option><option value="red-green">Red–green support</option><option value="blue-yellow">Blue–yellow support</option><option value="monochrome">Grayscale + labels</option></select></label>
      <label className="stt-field">Animation speed · {v.animationSpeed.toFixed(2)}× <SettingHelp text="Adjust trophy shine, tooltip auras, toast entrances and gradient drift. Does not change toast duration or sound. Animation-off preferences still win." /><input type="range" min="0.25" max="3" step="0.25" value={v.animationSpeed} onChange={e => set({animationSpeed:Number(e.target.value)})} /></label>
    </div><div className="stt-size-preview st-tier-shine">{(['bronze','silver','gold','platinum'] as const).map(tier => <TrophyGlyph key={tier} tier={tier} size={34} />)}<span>Live trophy & shine preview</span></div></fieldset>
    <fieldset className="stt-setting-group"><legend>Window & library details</legend><div className="stt-settings-grid">
      <SettingSwitch label="Remember where I left off" help="Reopen your last screen, search and library scroll position. Off opens the main library." checked={v.rememberScreen} onChange={rememberScreen => set({ rememberScreen })} />
      <SettingSwitch label="Blur Steam behind Trophies" help="Blur the Steam page that opened Trophies. Separate native Store/browser views may not support blur." checked={v.blurBackground} onChange={blurBackground => set({ blurBackground })} />
      <SettingSwitch label="Show scrollbar" help="Hide the scrollbar to reclaim its width. Wheel, touchpad and keyboard scrolling still work." checked={v.showScrollbar} onChange={showScrollbar => set({ showScrollbar })} />
      {v.showScrollbar && <><label className="stt-field">Scrollbar color <SettingHelp text="Change the scrollbar thumb color. This preview applies immediately." /><input type="color" value={v.scrollbarColor} onChange={e => set({ scrollbarColor:e.target.value })} /></label><label className="stt-field">Scrollbar thickness · {v.scrollbarWidth}px <SettingHelp text="Widen the vertical scrollbar. Thumb length follows how much content fits on screen." /><input type="range" min="2" max="18" value={v.scrollbarWidth} onChange={e => set({ scrollbarWidth:Number(e.target.value) })} /></label></>}
      <SettingSwitch label="Release year in library" help="Show the release year supplied by Steam next to game names. Unknown years stay hidden." checked={v.showReleaseYearLibrary} onChange={showReleaseYearLibrary => set({ showReleaseYearLibrary })} />
      <SettingSwitch label="Release year inside games" help="Show the release year next to the title above a game’s achievements." checked={v.showReleaseYearDetail} onChange={showReleaseYearDetail => set({ showReleaseYearDetail })} />
      <SettingSwitch label="Show completion rarity limit" help="Show an upper bound from the rarest achievement. Steam does not provide the exact percentage earning every achievement." checked={v.showCompletionRarity} onChange={showCompletionRarity => set({ showCompletionRarity })} />
      <SettingSwitch label="Show group rarity limits" help="Show the completion rarity upper bound beside each custom Base Game or expansion group." checked={v.showGroupRarity} onChange={showGroupRarity => set({ showGroupRarity })} />
      <label className="stt-field">Open achievement groups <SettingHelp text="Choose which groups start expanded when you enter a game. Set up groups in that game’s artwork/settings button." /><select value={v.groupExpansion} onChange={e => set({ groupExpansion:e.target.value as typeof v.groupExpansion })}><option value="all">Expand all</option><option value="base">Base game only</option><option value="none">Start collapsed</option></select></label>
    </div></fieldset>
    <fieldset className="stt-setting-group"><legend>Trophy recap</legend><div className="stt-settings-grid">
      <label className="stt-field">Starting period <SettingHelp text="Choose the recap that opens first. Changing its tabs also remembers your choice." /><select value={v.recapPeriod} onChange={e => set({recapPeriod:e.target.value as typeof v.recapPeriod})}><option value="week">Weekly · last 7 days</option><option value="month">Monthly · this month</option><option value="year">Yearly · this year</option></select></label>
      <SettingSwitch label="Include hidden games in recap" help="Count hidden games in your private recap without restoring them to the library." checked={v.recapIncludeHidden} onChange={recapIncludeHidden => set({recapIncludeHidden})} />
    </div></fieldset>
    <fieldset className="stt-setting-group"><legend>Tooltips & tier colors</legend><div className="stt-settings-grid">
      <label className="stt-field">Achievement tooltip layout <SettingHelp text="Choose title first, description first, or a compact title/date/rarity tooltip." /><select value={v.tooltipLayout} onChange={e => set({ tooltipLayout:e.target.value as typeof v.tooltipLayout })}><option value="standard">Title, description, date & rarity</option><option value="description-first">Description first</option><option value="compact">Compact · no description</option></select></label>
      <SettingSwitch label="Animate Bronze & Silver borders" help="Extend the shine and tooltip aura to Bronze and Silver. Their picture borders must also be enabled. Animation preferences still apply." checked={v.allTierEffects} onChange={allTierEffects => set({ allTierEffects })} />
      <SettingSwitch label="Use theme border colors" help="Let the theme recolor trophy borders. Your individual color overrides always win." checked={v.themeBorderColors} onChange={themeBorderColors => set({ themeBorderColors })} />
    </div>
    {(['trophyColors','tileColors','tooltipColors'] as const).map(kind => <fieldset key={kind} className="stt-setting-group"><legend>{kind === 'trophyColors' ? 'Trophy artwork tints' : kind === 'tileColors' ? 'Achievement picture borders' : 'Tooltip borders & glow'}</legend><div className="stt-settings-grid">{(['bronze','silver','gold','platinum'] as const).map(tier => <label className="stt-field" key={tier}>{tier[0].toUpperCase()+tier.slice(1)} <SettingHelp text={`Override the ${tier} ${kind === 'trophyColors' ? 'trophy artwork tint, preserving its shading' : kind === 'tileColors' ? 'picture border' : 'tooltip border and glow'}. Reset below restores automatic colors.`} /><input type="color" value={v[kind][tier] ?? (v.themeBorderColors ? theme : DEFAULT_THEME).tokens.color[tier]} onChange={e => set({ [kind]:{ ...v[kind], [tier]:e.target.value } })} /></label>)}</div><button className="st-mini-button" title="Remove only these color overrides" onClick={() => set({ [kind]:{} })}>Reset these colors</button></fieldset>)}
    <div className="stt-size-preview" aria-label="Live border colors preview">{(['bronze','silver','gold','platinum'] as const).map(tier => <span key={tier} style={{ padding:6, border:`2px solid var(--stt-tooltip-${tier})`, borderRadius:8 }}><TrophyGlyph tier={tier} size={30} /></span>)}<span>Live border preview</span></div>
    </fieldset>
    <fieldset className="stt-setting-group"><legend>Custom theme</legend>
      <SettingSwitch label="Use my custom colors" help="Layer your colors over the selected theme. Turning this off keeps your custom palette saved." checked={v.customThemeEnabled} onChange={customThemeEnabled => set({ customThemeEnabled })} />
      {v.customThemeEnabled && <><div className="stt-settings-grid">{(['background','surface','surfaceRaised','text','muted','accent','border','focus'] as const).map(key => <label key={key} className="stt-field">{({ background:'Background',surface:'Cards',surfaceRaised:'Raised cards',text:'Text',muted:'Secondary text',accent:'Accent & progress',border:'Control borders',focus:'Keyboard focus' })[key]} <SettingHelp text="Apply this color immediately. Keep text easy to read against the background." /><input type="color" value={v.customColors[key] ?? (/^#[\da-f]{6}$/i.test(theme.tokens.color[key]) ? theme.tokens.color[key] : '#56616e')} onChange={e => set({ customColors:{ ...v.customColors,[key]:e.target.value } })} /></label>)}</div>
      <div className="stt-settings-grid"><label className="stt-field">Background gradient <SettingHelp text="Blend the background into your second color. Solid turns the blend off." /><select value={v.gradient} onChange={e => set({ gradient:e.target.value as typeof v.gradient })}><option value="none">Solid</option><option value="diagonal">Diagonal</option><option value="horizontal">Horizontal</option></select></label><label className="stt-field">Second gradient color <SettingHelp text="Choose the other end of your background color blend." /><input type="color" value={v.gradientColor} onChange={e => set({ gradientColor:e.target.value })} /></label><SettingSwitch label="Slow gradient drift" help="Gently move the background gradient. No flashing; reduced motion disables it." checked={v.backgroundAnimation === 'drift'} onChange={checked => set({ backgroundAnimation:checked ? 'drift' : 'none' })} /></div>
      <button className="st-mini-button" title="Reset custom palette without changing trophy border overrides" onClick={() => set({ customColors:{},gradient:'none',backgroundAnimation:'none' })}>Reset custom theme</button></>}
    </fieldset>
  </section>;
}
